#!/usr/bin/env python2
# -*- coding: utf-8 -*-
import os, sys

def colora(i, string):
	return "\033[%d;1m%s\033[0m" % (i, string)

# Prendo i dati
try:
	cosa = sys.argv[1] # path del file 
except:
	print(colora(31, "Inserisci il file"))
	sys.exit()

try:
	dove = sys.argv[2] # dove copiare il file        
except:
	print(colora(31, "\t...e dove volevi metterlo?"))
	print(colora(31, "\t Lo metto in ~"))
        dove = ""

user = 'wpagvdfy'
host = 'srv-hs11.netsons.net'

print ("Copio %s --> scp %s@%s:~/%s" % (cosa, colora(31,user), colora(32,host), dove ))
os.system("scp -P65100 %s %s@%s:~/%s" % (cosa, user, host, dove))
