#!/bin/bash
# script di Gianmarco Brocchi - Gimmy per rimuovere le cartelle vuote

if [ -z $1 ]
then
	DEPTH=3 # profondità di ricerca di default
else
	DEPTH=$1
fi

FOUND=$(find . -maxdepth $DEPTH -type d -empty -exec echo {} \;) # cerca e stampa le cartelle vuote

if [ -z $FOUND ]
then
	echo "Nessuna cartella vuota a questa profondità"
else
	find . -maxdepth $DEPTH -type d -empty -exec echo {} \; # stampa le cartelle vuote
	echo "Rimuovere le cartelle vuote? [y/n]"; read Rm
	if [ $Rm == 'y' ]; then
		find . -maxdepth $DEPTH -type d -empty -exec rmdir -v -p {} \; # rimuovo parents con verbose
	else
		exit
	fi
fi
