#!/usr/bin/python
# Gianmarco Brocchi

'''

Script that help to restore files
from a Deja-dup backup by hand.

Use ./restorehelp multivolume_snapshot_path

It merges the file in multivolume_snapshot.

'''

import os, sys
#from subprocess import call
from glob import iglob
import shutil

try:
	rootdir = sys.argv[1]
except:
	print "Insert the multivolume_snapshot's path"
	sys.exit()
	
for root, subFolders, files in os.walk(rootdir):

	for filename in files:
		if filename == "1":
			filePath = os.path.join(root)
			folder = os.path.basename(filePath)
			# outfile = filePath.replace('multivol_','',1) 
			outfile = filePath + "/" + folder
			print outfile

#	Implement "cat * > folder"
#			call(["cat " + all_file + ">" + outfile], shell=True)

# Check if file exists
			if ( os.path.exists(outfile) == False ):
				destination = open(outfile, 'wb')
				for filename in iglob(os.path.join(filePath, '*')):
					shutil.copyfileobj(open(filename, 'rb'), destination)
				destination.close()
				print "Creo file: %s" % folder
			else:
				print "File %s exists" % folder	
	
